name:                lnd-client
version:             0.1.0.0
github:              "githubuser/lnd-client"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lnd-client#readme>

#
# TODO : rm unused dependencies!!!
#
dependencies:
# foundation
- base                  >= 4.7 && < 5
- universum             >= 1.5.0 && < 1.5.1
# time
- chronos               >= 1.0.9 && < 1.0.10
- unbounded-delays      >= 0.1.1.0 && < 0.1.2
# storage
- persistent            >= 2.11.0.2 && < 2.11.1
# logging
- katip                 >= 0.8.3.0 && < 0.8.4
# byte and text
- bytestring            >= 0.10.8.2 && < 0.10.9
- base16-bytestring     >= 1.0.1.0 && < 1.0.2
- base64-bytestring     >= 1.0.0.3 && <  1.0.1
- text                  >= 1.2.3.1 && < 1.2.4
- aeson                 >= 1.4.6.0 && < 1.4.7
# protobuf and gRPC
- containers            >= 0.6.0.1 && < 0.6.1
- deepseq               >= 1.4.4.0 && < 1.4.5
- vector                >= 0.12.1.2 && < 0.12.2
# images
- qrcode-core           >= 0.9.2 && < 0.9.3
- qrcode-juicypixels    >= 0.8.0 && < 0.8.1
- JuicyPixels           >= 3.3.4 && < 3.3.5
# system and threading
- envparse              >= 0.4.1 && < 0.4.2
- async                 >= 2.2.2 && < 2.2.3
- stm                   >= 2.5.0.0 && < 2.5.1
# crypto
- cryptonite            >= 0.26 && < 0.27
- cryptohash-sha256     >= 0.11.101.0 && < 0.11.102
- x509                  >= 1.7.5 && < 1.7.6
- asn1-encoding         >= 0.9.6 && < 0.10
- asn1-types            >= 0.3 && < 0.4
- pem                   >= 0.2.4 && < 0.3
# bitcoin
- network-bitcoin       >= 1.9.1 && < 1.9.2
# general
- unliftio              >= 0.2.12 && < 0.2.13
- extra                 >= 1.6.19 && < 1.6.20
- scientific            >= 0.3.6.2 && < 0.3.7
- template-haskell      >= 2.14.0.0 && < 2.14.1
# protobuf
- microlens             >= 0.4.10 && < 0.5
- proto-lens            >= 0.6.0.0 && < 0.6.1
- proto-lens-runtime    >= 0.6.0.0 && < 0.6.1
# proto-lens-grpc
- http2-grpc-proto-lens >= 0.1.0.0 && < 0.1.1
- http2-client          >= 0.9.0.0 && < 0.9.1
- http2-client-grpc     >= 0.8.0.0 && < 0.8.1
- http2-grpc-types      >= 0.5.0.0 && < 0.5.1
- http2                 >= 1.6.5 && < 1.6.6

library:
  source-dirs: src
  default-extensions:
  - NoImplicitPrelude
  - MultiParamTypeClasses
  - LambdaCase
  - OverloadedStrings
  - ScopedTypeVariables
  - DataKinds
  - KindSignatures
  ghc-options:
  # For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
  # Enable all warnings with -Weverything, then disable the ones we don’t care about
  - -Weverything
  - -Werror
  - -Wno-missing-export-lists
  - -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
  - -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
  - -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
  - -Wno-all-missed-specialisations # See missed-specialisations
  - -Wno-unsafe # Don’t use Safe Haskell warnings
  - -Wno-safe # Don’t use Safe Haskell warnings
  - -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
  - -Wno-monomorphism-restriction # Don’t warn if the monomorphism restriction is used
  #- -optl-fuse-ld=gold
  #ld-options:
  #- -fuse-ld=gold
  dependencies:
  - hspec >= 2.7.1 && < 2.7.2

tests:
  lnd-client-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
    - NoImplicitPrelude
    - MultiParamTypeClasses
    - LambdaCase
    - OverloadedStrings
    - ScopedTypeVariables
    - DataKinds
    - KindSignatures
    ghc-options:
    # For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
    # Enable all warnings with -Weverything, then disable the ones we don’t care about
    - -Weverything
    - -Werror
    - -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
    - -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
    - -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
    - -Wno-all-missed-specialisations # See missed-specialisations
    - -Wno-unsafe # Don’t use Safe Haskell warnings
    - -Wno-safe # Don’t use Safe Haskell warnings
    - -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
    - -Wno-monomorphism-restriction # Don’t warn if the monomorphism restriction is used
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    #- -optl-fuse-ld=gold
    #ld-options:
    #- -fuse-ld=gold
    dependencies:
    - lnd-client
    - hspec >= 2.7.1 && < 2.7.2

