configure: &configure
  docker:
  - image: nixos/nix:2.3
  resource_class: xlarge

release: &release
  run:
    name: Create release
    command: ./nix/release.sh
    no_output_timeout: 60m

filters: &filters
  filters:
    branches: {}

version: 2
jobs:
  release:
    <<: *configure
    steps:
    - checkout
    - setup_remote_docker
    - *release

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          <<: *filters
          cron: "0 5 * * *"  # 05:00 UTC
    jobs:
      - release:
          <<: *filters
          context: global
  push:
    jobs:
      - release:
          <<: *filters
          context: global