{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# OPTIONS_GHC -Wno-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module InvoiceGrpc where

import qualified Control.Applicative as Hs
import Control.Applicative ((<$>), (<*>), (<|>))
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs (Int16, Int32, Int64)
import qualified Data.List.NonEmpty as Hs (NonEmpty (..))
import qualified Data.Map as Hs (Map, mapKeysMonotonic)
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs (fromString)
import qualified Data.Text.Lazy as Hs (Text)
import qualified Data.Vector as Hs (Vector)
import qualified Data.Word as Hs (Word16, Word32, Word64)
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified LndGrpc
import Network.GRPC.HighLevel.Client as HsGRPC
import Network.GRPC.HighLevel.Generated as HsGRPC
import Network.GRPC.HighLevel.Server as HsGRPC hiding (serverLoop)
import Network.GRPC.HighLevel.Server.Unregistered as HsGRPC
  ( serverLoop,
  )
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobuf
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ((.:), (.=))
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Unsafe.Coerce as Hs
import qualified Prelude as Hs

data
  Invoices
    request
    response
  = Invoices
      { invoicesSubscribeSingleInvoice ::
          request 'HsGRPC.ServerStreaming
            InvoiceGrpc.SubscribeSingleInvoiceRequest
            LndGrpc.Invoice ->
          Hs.IO (response 'HsGRPC.ServerStreaming LndGrpc.Invoice),
        invoicesCancelInvoice ::
          request 'HsGRPC.Normal InvoiceGrpc.CancelInvoiceMsg
            InvoiceGrpc.CancelInvoiceResp ->
          Hs.IO (response 'HsGRPC.Normal InvoiceGrpc.CancelInvoiceResp),
        invoicesAddHoldInvoice ::
          request 'HsGRPC.Normal InvoiceGrpc.AddHoldInvoiceRequest
            InvoiceGrpc.AddHoldInvoiceResp ->
          Hs.IO (response 'HsGRPC.Normal InvoiceGrpc.AddHoldInvoiceResp),
        invoicesSettleInvoice ::
          request 'HsGRPC.Normal InvoiceGrpc.SettleInvoiceMsg
            InvoiceGrpc.SettleInvoiceResp ->
          Hs.IO (response 'HsGRPC.Normal InvoiceGrpc.SettleInvoiceResp)
      }
  deriving (Hs.Generic)

invoicesServer ::
  Invoices HsGRPC.ServerRequest HsGRPC.ServerResponse ->
  HsGRPC.ServiceOptions ->
  Hs.IO ()
invoicesServer
  Invoices
    { invoicesSubscribeSingleInvoice =
        invoicesSubscribeSingleInvoice,
      invoicesCancelInvoice = invoicesCancelInvoice,
      invoicesAddHoldInvoice = invoicesAddHoldInvoice,
      invoicesSettleInvoice = invoicesSettleInvoice
    }
  ( ServiceOptions
      serverHost
      serverPort
      useCompression
      userAgentPrefix
      userAgentSuffix
      initialMetadata
      sslConfig
      logger
    ) =
    ( HsGRPC.serverLoop
        HsGRPC.defaultOptions
          { HsGRPC.optNormalHandlers =
              [ ( HsGRPC.UnaryHandler
                    (HsGRPC.MethodName "/invoicesrpc.Invoices/CancelInvoice")
                    (HsGRPC.convertGeneratedServerHandler invoicesCancelInvoice)
                ),
                ( HsGRPC.UnaryHandler
                    (HsGRPC.MethodName "/invoicesrpc.Invoices/AddHoldInvoice")
                    (HsGRPC.convertGeneratedServerHandler invoicesAddHoldInvoice)
                ),
                ( HsGRPC.UnaryHandler
                    (HsGRPC.MethodName "/invoicesrpc.Invoices/SettleInvoice")
                    (HsGRPC.convertGeneratedServerHandler invoicesSettleInvoice)
                )
              ],
            HsGRPC.optClientStreamHandlers = [],
            HsGRPC.optServerStreamHandlers =
              [ ( HsGRPC.ServerStreamHandler
                    ( HsGRPC.MethodName
                        "/invoicesrpc.Invoices/SubscribeSingleInvoice"
                    )
                    ( HsGRPC.convertGeneratedServerWriterHandler
                        invoicesSubscribeSingleInvoice
                    )
                )
              ],
            HsGRPC.optBiDiStreamHandlers = [],
            optServerHost = serverHost,
            optServerPort = serverPort,
            optUseCompression = useCompression,
            optUserAgentPrefix = userAgentPrefix,
            optUserAgentSuffix = userAgentSuffix,
            optInitialMetadata = initialMetadata,
            optSSLConfig = sslConfig,
            optLogger = logger
          }
    )

invoicesClient ::
  HsGRPC.Client ->
  Hs.IO (Invoices HsGRPC.ClientRequest HsGRPC.ClientResult)
invoicesClient client =
  (Hs.pure Invoices)
    <*> ( (Hs.pure (HsGRPC.clientRequest client))
            <*> ( HsGRPC.clientRegisterMethod
                    client
                    ( HsGRPC.MethodName
                        "/invoicesrpc.Invoices/SubscribeSingleInvoice"
                    )
                )
        )
    <*> ( (Hs.pure (HsGRPC.clientRequest client))
            <*> ( HsGRPC.clientRegisterMethod
                    client
                    (HsGRPC.MethodName "/invoicesrpc.Invoices/CancelInvoice")
                )
        )
    <*> ( (Hs.pure (HsGRPC.clientRequest client))
            <*> ( HsGRPC.clientRegisterMethod
                    client
                    (HsGRPC.MethodName "/invoicesrpc.Invoices/AddHoldInvoice")
                )
        )
    <*> ( (Hs.pure (HsGRPC.clientRequest client))
            <*> ( HsGRPC.clientRegisterMethod
                    client
                    (HsGRPC.MethodName "/invoicesrpc.Invoices/SettleInvoice")
                )
        )

data CancelInvoiceMsg
  = CancelInvoiceMsg
      { cancelInvoiceMsgPaymentHash ::
          Hs.ByteString
      }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)

instance HsProtobuf.Named CancelInvoiceMsg where
  nameOf _ = (Hs.fromString "CancelInvoiceMsg")

instance HsProtobuf.HasDefault CancelInvoiceMsg

instance HsProtobuf.Message CancelInvoiceMsg where
  encodeMessage
    _
    CancelInvoiceMsg
      { cancelInvoiceMsgPaymentHash =
          cancelInvoiceMsgPaymentHash
      } =
      ( Hs.mconcat
          [ ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                cancelInvoiceMsgPaymentHash
            )
          ]
      )
  decodeMessage _ =
    (Hs.pure CancelInvoiceMsg)
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 1)
          )
  dotProto _ =
    [ ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 1)
          (HsProtobuf.Prim HsProtobuf.Bytes)
          (HsProtobuf.Single "payment_hash")
          []
          ""
      )
    ]

instance HsJSONPB.ToJSONPB CancelInvoiceMsg where
  toJSONPB (CancelInvoiceMsg f1) =
    (HsJSONPB.object ["payment_hash" .= f1])
  toEncodingPB (CancelInvoiceMsg f1) =
    (HsJSONPB.pairs ["payment_hash" .= f1])

instance HsJSONPB.FromJSONPB CancelInvoiceMsg where
  parseJSONPB =
    ( HsJSONPB.withObject
        "CancelInvoiceMsg"
        (\obj -> (Hs.pure CancelInvoiceMsg) <*> obj .: "payment_hash")
    )

instance HsJSONPB.ToJSON CancelInvoiceMsg where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance HsJSONPB.FromJSON CancelInvoiceMsg where
  parseJSON = HsJSONPB.parseJSONPB

instance HsJSONPB.ToSchema CancelInvoiceMsg where
  declareNamedSchema _ =
    do
      let declare_payment_hash = HsJSONPB.declareSchemaRef
      cancelInvoiceMsgPaymentHash <- declare_payment_hash Proxy.Proxy
      let _ =
            Hs.pure CancelInvoiceMsg
              <*> HsJSONPB.asProxy declare_payment_hash
      Hs.return
        ( HsJSONPB.NamedSchema
            { HsJSONPB._namedSchemaName =
                Hs.Just "CancelInvoiceMsg",
              HsJSONPB._namedSchemaSchema =
                Hs.mempty
                  { HsJSONPB._schemaParamSchema =
                      Hs.mempty
                        { HsJSONPB._paramSchemaType =
                            HsJSONPB.SwaggerObject
                        },
                    HsJSONPB._schemaProperties =
                      HsJSONPB.insOrdFromList
                        [ ( "payment_hash",
                            cancelInvoiceMsgPaymentHash
                          )
                        ]
                  }
            }
        )

data CancelInvoiceResp = CancelInvoiceResp {}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)

instance HsProtobuf.Named CancelInvoiceResp where
  nameOf _ = (Hs.fromString "CancelInvoiceResp")

instance HsProtobuf.HasDefault CancelInvoiceResp

instance HsProtobuf.Message CancelInvoiceResp where
  encodeMessage _ CancelInvoiceResp {} = (Hs.mconcat [])
  decodeMessage _ = (Hs.pure CancelInvoiceResp)
  dotProto _ = []

instance HsJSONPB.ToJSONPB CancelInvoiceResp where
  toJSONPB (CancelInvoiceResp) = (HsJSONPB.object [])
  toEncodingPB (CancelInvoiceResp) = (HsJSONPB.pairs [])

instance HsJSONPB.FromJSONPB CancelInvoiceResp where
  parseJSONPB =
    ( HsJSONPB.withObject
        "CancelInvoiceResp"
        (\obj -> (Hs.pure CancelInvoiceResp))
    )

instance HsJSONPB.ToJSON CancelInvoiceResp where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance HsJSONPB.FromJSON CancelInvoiceResp where
  parseJSON = HsJSONPB.parseJSONPB

instance HsJSONPB.ToSchema CancelInvoiceResp where
  declareNamedSchema _ =
    do
      Hs.return
        ( HsJSONPB.NamedSchema
            { HsJSONPB._namedSchemaName =
                Hs.Just "CancelInvoiceResp",
              HsJSONPB._namedSchemaSchema =
                Hs.mempty
                  { HsJSONPB._schemaParamSchema =
                      Hs.mempty
                        { HsJSONPB._paramSchemaType =
                            HsJSONPB.SwaggerObject
                        },
                    HsJSONPB._schemaProperties =
                      HsJSONPB.insOrdFromList []
                  }
            }
        )

data AddHoldInvoiceRequest
  = AddHoldInvoiceRequest
      { addHoldInvoiceRequestMemo ::
          Hs.Text,
        addHoldInvoiceRequestHash :: Hs.ByteString,
        addHoldInvoiceRequestValue :: Hs.Int64,
        addHoldInvoiceRequestValueMsat :: Hs.Int64,
        addHoldInvoiceRequestDescriptionHash ::
          Hs.ByteString,
        addHoldInvoiceRequestExpiry :: Hs.Int64,
        addHoldInvoiceRequestFallbackAddr :: Hs.Text,
        addHoldInvoiceRequestCltvExpiry :: Hs.Word64,
        addHoldInvoiceRequestRouteHints ::
          Hs.Vector
            LndGrpc.RouteHint,
        addHoldInvoiceRequestPrivate :: Hs.Bool
      }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)

instance HsProtobuf.Named AddHoldInvoiceRequest where
  nameOf _ = (Hs.fromString "AddHoldInvoiceRequest")

instance HsProtobuf.HasDefault AddHoldInvoiceRequest

instance HsProtobuf.Message AddHoldInvoiceRequest where
  encodeMessage
    _
    AddHoldInvoiceRequest
      { addHoldInvoiceRequestMemo =
          addHoldInvoiceRequestMemo,
        addHoldInvoiceRequestHash = addHoldInvoiceRequestHash,
        addHoldInvoiceRequestValue = addHoldInvoiceRequestValue,
        addHoldInvoiceRequestValueMsat = addHoldInvoiceRequestValueMsat,
        addHoldInvoiceRequestDescriptionHash =
          addHoldInvoiceRequestDescriptionHash,
        addHoldInvoiceRequestExpiry = addHoldInvoiceRequestExpiry,
        addHoldInvoiceRequestFallbackAddr =
          addHoldInvoiceRequestFallbackAddr,
        addHoldInvoiceRequestCltvExpiry = addHoldInvoiceRequestCltvExpiry,
        addHoldInvoiceRequestRouteHints = addHoldInvoiceRequestRouteHints,
        addHoldInvoiceRequestPrivate = addHoldInvoiceRequestPrivate
      } =
      ( Hs.mconcat
          [ ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                addHoldInvoiceRequestMemo
            ),
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                addHoldInvoiceRequestHash
            ),
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 3)
                addHoldInvoiceRequestValue
            ),
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 10)
                addHoldInvoiceRequestValueMsat
            ),
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 4)
                addHoldInvoiceRequestDescriptionHash
            ),
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 5)
                addHoldInvoiceRequestExpiry
            ),
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 6)
                addHoldInvoiceRequestFallbackAddr
            ),
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 7)
                addHoldInvoiceRequestCltvExpiry
            ),
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 8)
                ( Hs.coerce @(Hs.Vector LndGrpc.RouteHint)
                    @(HsProtobuf.NestedVec LndGrpc.RouteHint)
                    addHoldInvoiceRequestRouteHints
                )
            ),
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 9)
                addHoldInvoiceRequestPrivate
            )
          ]
      )
  decodeMessage _ =
    (Hs.pure AddHoldInvoiceRequest)
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 1)
          )
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 2)
          )
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 3)
          )
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 10)
          )
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 4)
          )
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 5)
          )
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 6)
          )
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 7)
          )
      <*> ( Hs.coerce @(_ (HsProtobuf.NestedVec LndGrpc.RouteHint))
              @(_ (Hs.Vector LndGrpc.RouteHint))
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 8)
              )
          )
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 9)
          )
  dotProto _ =
    [ ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 1)
          (HsProtobuf.Prim HsProtobuf.String)
          (HsProtobuf.Single "memo")
          []
          ""
      ),
      ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 2)
          (HsProtobuf.Prim HsProtobuf.Bytes)
          (HsProtobuf.Single "hash")
          []
          ""
      ),
      ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 3)
          (HsProtobuf.Prim HsProtobuf.Int64)
          (HsProtobuf.Single "value")
          []
          ""
      ),
      ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 10)
          (HsProtobuf.Prim HsProtobuf.Int64)
          (HsProtobuf.Single "value_msat")
          []
          ""
      ),
      ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 4)
          (HsProtobuf.Prim HsProtobuf.Bytes)
          (HsProtobuf.Single "description_hash")
          []
          ""
      ),
      ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 5)
          (HsProtobuf.Prim HsProtobuf.Int64)
          (HsProtobuf.Single "expiry")
          []
          ""
      ),
      ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 6)
          (HsProtobuf.Prim HsProtobuf.String)
          (HsProtobuf.Single "fallback_addr")
          []
          ""
      ),
      ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 7)
          (HsProtobuf.Prim HsProtobuf.UInt64)
          (HsProtobuf.Single "cltv_expiry")
          []
          ""
      ),
      ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 8)
          ( HsProtobuf.Repeated
              ( HsProtobuf.Named
                  (HsProtobuf.Dots (HsProtobuf.Path ("lnrpc" Hs.:| ["RouteHint"])))
              )
          )
          (HsProtobuf.Single "route_hints")
          []
          ""
      ),
      ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 9)
          (HsProtobuf.Prim HsProtobuf.Bool)
          (HsProtobuf.Single "private")
          []
          ""
      )
    ]

instance HsJSONPB.ToJSONPB AddHoldInvoiceRequest where
  toJSONPB (AddHoldInvoiceRequest f1 f2 f3 f10 f4 f5 f6 f7 f8 f9) =
    ( HsJSONPB.object
        [ "memo" .= f1,
          "hash" .= f2,
          "value" .= f3,
          "value_msat" .= f10,
          "description_hash" .= f4,
          "expiry" .= f5,
          "fallback_addr" .= f6,
          "cltv_expiry" .= f7,
          "route_hints" .= f8,
          "private" .= f9
        ]
    )
  toEncodingPB (AddHoldInvoiceRequest f1 f2 f3 f10 f4 f5 f6 f7 f8 f9) =
    ( HsJSONPB.pairs
        [ "memo" .= f1,
          "hash" .= f2,
          "value" .= f3,
          "value_msat" .= f10,
          "description_hash" .= f4,
          "expiry" .= f5,
          "fallback_addr" .= f6,
          "cltv_expiry" .= f7,
          "route_hints" .= f8,
          "private" .= f9
        ]
    )

instance HsJSONPB.FromJSONPB AddHoldInvoiceRequest where
  parseJSONPB =
    ( HsJSONPB.withObject
        "AddHoldInvoiceRequest"
        ( \obj ->
            (Hs.pure AddHoldInvoiceRequest) <*> obj .: "memo" <*> obj .: "hash"
              <*> obj .: "value"
              <*> obj .: "value_msat"
              <*> obj .: "description_hash"
              <*> obj .: "expiry"
              <*> obj .: "fallback_addr"
              <*> obj .: "cltv_expiry"
              <*> obj .: "route_hints"
              <*> obj .: "private"
        )
    )

instance HsJSONPB.ToJSON AddHoldInvoiceRequest where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance HsJSONPB.FromJSON AddHoldInvoiceRequest where
  parseJSON = HsJSONPB.parseJSONPB

instance HsJSONPB.ToSchema AddHoldInvoiceRequest where
  declareNamedSchema _ =
    do
      let declare_memo = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestMemo <- declare_memo Proxy.Proxy
      let declare_hash = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestHash <- declare_hash Proxy.Proxy
      let declare_value = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestValue <- declare_value Proxy.Proxy
      let declare_value_msat = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestValueMsat <- declare_value_msat Proxy.Proxy
      let declare_description_hash = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestDescriptionHash <-
        declare_description_hash
          Proxy.Proxy
      let declare_expiry = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestExpiry <- declare_expiry Proxy.Proxy
      let declare_fallback_addr = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestFallbackAddr <-
        declare_fallback_addr
          Proxy.Proxy
      let declare_cltv_expiry = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestCltvExpiry <- declare_cltv_expiry Proxy.Proxy
      let declare_route_hints = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestRouteHints <- declare_route_hints Proxy.Proxy
      let declare_private = HsJSONPB.declareSchemaRef
      addHoldInvoiceRequestPrivate <- declare_private Proxy.Proxy
      let _ =
            Hs.pure AddHoldInvoiceRequest
              <*> HsJSONPB.asProxy declare_memo
              <*> HsJSONPB.asProxy declare_hash
              <*> HsJSONPB.asProxy declare_value
              <*> HsJSONPB.asProxy declare_value_msat
              <*> HsJSONPB.asProxy declare_description_hash
              <*> HsJSONPB.asProxy declare_expiry
              <*> HsJSONPB.asProxy declare_fallback_addr
              <*> HsJSONPB.asProxy declare_cltv_expiry
              <*> HsJSONPB.asProxy declare_route_hints
              <*> HsJSONPB.asProxy declare_private
      Hs.return
        ( HsJSONPB.NamedSchema
            { HsJSONPB._namedSchemaName =
                Hs.Just "AddHoldInvoiceRequest",
              HsJSONPB._namedSchemaSchema =
                Hs.mempty
                  { HsJSONPB._schemaParamSchema =
                      Hs.mempty
                        { HsJSONPB._paramSchemaType =
                            HsJSONPB.SwaggerObject
                        },
                    HsJSONPB._schemaProperties =
                      HsJSONPB.insOrdFromList
                        [ ("memo", addHoldInvoiceRequestMemo),
                          ("hash", addHoldInvoiceRequestHash),
                          ("value", addHoldInvoiceRequestValue),
                          ( "value_msat",
                            addHoldInvoiceRequestValueMsat
                          ),
                          ( "description_hash",
                            addHoldInvoiceRequestDescriptionHash
                          ),
                          ("expiry", addHoldInvoiceRequestExpiry),
                          ( "fallback_addr",
                            addHoldInvoiceRequestFallbackAddr
                          ),
                          ( "cltv_expiry",
                            addHoldInvoiceRequestCltvExpiry
                          ),
                          ( "route_hints",
                            addHoldInvoiceRequestRouteHints
                          ),
                          ( "private",
                            addHoldInvoiceRequestPrivate
                          )
                        ]
                  }
            }
        )

data AddHoldInvoiceResp
  = AddHoldInvoiceResp
      { addHoldInvoiceRespPaymentRequest ::
          Hs.Text
      }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)

instance HsProtobuf.Named AddHoldInvoiceResp where
  nameOf _ = (Hs.fromString "AddHoldInvoiceResp")

instance HsProtobuf.HasDefault AddHoldInvoiceResp

instance HsProtobuf.Message AddHoldInvoiceResp where
  encodeMessage
    _
    AddHoldInvoiceResp
      { addHoldInvoiceRespPaymentRequest =
          addHoldInvoiceRespPaymentRequest
      } =
      ( Hs.mconcat
          [ ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                addHoldInvoiceRespPaymentRequest
            )
          ]
      )
  decodeMessage _ =
    (Hs.pure AddHoldInvoiceResp)
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 1)
          )
  dotProto _ =
    [ ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 1)
          (HsProtobuf.Prim HsProtobuf.String)
          (HsProtobuf.Single "payment_request")
          []
          ""
      )
    ]

instance HsJSONPB.ToJSONPB AddHoldInvoiceResp where
  toJSONPB (AddHoldInvoiceResp f1) =
    (HsJSONPB.object ["payment_request" .= f1])
  toEncodingPB (AddHoldInvoiceResp f1) =
    (HsJSONPB.pairs ["payment_request" .= f1])

instance HsJSONPB.FromJSONPB AddHoldInvoiceResp where
  parseJSONPB =
    ( HsJSONPB.withObject
        "AddHoldInvoiceResp"
        ( \obj ->
            (Hs.pure AddHoldInvoiceResp) <*> obj .: "payment_request"
        )
    )

instance HsJSONPB.ToJSON AddHoldInvoiceResp where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance HsJSONPB.FromJSON AddHoldInvoiceResp where
  parseJSON = HsJSONPB.parseJSONPB

instance HsJSONPB.ToSchema AddHoldInvoiceResp where
  declareNamedSchema _ =
    do
      let declare_payment_request = HsJSONPB.declareSchemaRef
      addHoldInvoiceRespPaymentRequest <-
        declare_payment_request
          Proxy.Proxy
      let _ =
            Hs.pure AddHoldInvoiceResp
              <*> HsJSONPB.asProxy declare_payment_request
      Hs.return
        ( HsJSONPB.NamedSchema
            { HsJSONPB._namedSchemaName =
                Hs.Just "AddHoldInvoiceResp",
              HsJSONPB._namedSchemaSchema =
                Hs.mempty
                  { HsJSONPB._schemaParamSchema =
                      Hs.mempty
                        { HsJSONPB._paramSchemaType =
                            HsJSONPB.SwaggerObject
                        },
                    HsJSONPB._schemaProperties =
                      HsJSONPB.insOrdFromList
                        [ ( "payment_request",
                            addHoldInvoiceRespPaymentRequest
                          )
                        ]
                  }
            }
        )

data SettleInvoiceMsg
  = SettleInvoiceMsg
      { settleInvoiceMsgPreimage ::
          Hs.ByteString
      }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)

instance HsProtobuf.Named SettleInvoiceMsg where
  nameOf _ = (Hs.fromString "SettleInvoiceMsg")

instance HsProtobuf.HasDefault SettleInvoiceMsg

instance HsProtobuf.Message SettleInvoiceMsg where
  encodeMessage
    _
    SettleInvoiceMsg
      { settleInvoiceMsgPreimage =
          settleInvoiceMsgPreimage
      } =
      ( Hs.mconcat
          [ ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                settleInvoiceMsgPreimage
            )
          ]
      )
  decodeMessage _ =
    (Hs.pure SettleInvoiceMsg)
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 1)
          )
  dotProto _ =
    [ ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 1)
          (HsProtobuf.Prim HsProtobuf.Bytes)
          (HsProtobuf.Single "preimage")
          []
          ""
      )
    ]

instance HsJSONPB.ToJSONPB SettleInvoiceMsg where
  toJSONPB (SettleInvoiceMsg f1) =
    (HsJSONPB.object ["preimage" .= f1])
  toEncodingPB (SettleInvoiceMsg f1) =
    (HsJSONPB.pairs ["preimage" .= f1])

instance HsJSONPB.FromJSONPB SettleInvoiceMsg where
  parseJSONPB =
    ( HsJSONPB.withObject
        "SettleInvoiceMsg"
        (\obj -> (Hs.pure SettleInvoiceMsg) <*> obj .: "preimage")
    )

instance HsJSONPB.ToJSON SettleInvoiceMsg where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance HsJSONPB.FromJSON SettleInvoiceMsg where
  parseJSON = HsJSONPB.parseJSONPB

instance HsJSONPB.ToSchema SettleInvoiceMsg where
  declareNamedSchema _ =
    do
      let declare_preimage = HsJSONPB.declareSchemaRef
      settleInvoiceMsgPreimage <- declare_preimage Proxy.Proxy
      let _ =
            Hs.pure SettleInvoiceMsg
              <*> HsJSONPB.asProxy declare_preimage
      Hs.return
        ( HsJSONPB.NamedSchema
            { HsJSONPB._namedSchemaName =
                Hs.Just "SettleInvoiceMsg",
              HsJSONPB._namedSchemaSchema =
                Hs.mempty
                  { HsJSONPB._schemaParamSchema =
                      Hs.mempty
                        { HsJSONPB._paramSchemaType =
                            HsJSONPB.SwaggerObject
                        },
                    HsJSONPB._schemaProperties =
                      HsJSONPB.insOrdFromList
                        [("preimage", settleInvoiceMsgPreimage)]
                  }
            }
        )

data SettleInvoiceResp = SettleInvoiceResp {}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)

instance HsProtobuf.Named SettleInvoiceResp where
  nameOf _ = (Hs.fromString "SettleInvoiceResp")

instance HsProtobuf.HasDefault SettleInvoiceResp

instance HsProtobuf.Message SettleInvoiceResp where
  encodeMessage _ SettleInvoiceResp {} = (Hs.mconcat [])
  decodeMessage _ = (Hs.pure SettleInvoiceResp)
  dotProto _ = []

instance HsJSONPB.ToJSONPB SettleInvoiceResp where
  toJSONPB (SettleInvoiceResp) = (HsJSONPB.object [])
  toEncodingPB (SettleInvoiceResp) = (HsJSONPB.pairs [])

instance HsJSONPB.FromJSONPB SettleInvoiceResp where
  parseJSONPB =
    ( HsJSONPB.withObject
        "SettleInvoiceResp"
        (\obj -> (Hs.pure SettleInvoiceResp))
    )

instance HsJSONPB.ToJSON SettleInvoiceResp where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance HsJSONPB.FromJSON SettleInvoiceResp where
  parseJSON = HsJSONPB.parseJSONPB

instance HsJSONPB.ToSchema SettleInvoiceResp where
  declareNamedSchema _ =
    do
      Hs.return
        ( HsJSONPB.NamedSchema
            { HsJSONPB._namedSchemaName =
                Hs.Just "SettleInvoiceResp",
              HsJSONPB._namedSchemaSchema =
                Hs.mempty
                  { HsJSONPB._schemaParamSchema =
                      Hs.mempty
                        { HsJSONPB._paramSchemaType =
                            HsJSONPB.SwaggerObject
                        },
                    HsJSONPB._schemaProperties =
                      HsJSONPB.insOrdFromList []
                  }
            }
        )

data SubscribeSingleInvoiceRequest
  = SubscribeSingleInvoiceRequest
      { subscribeSingleInvoiceRequestRHash ::
          Hs.ByteString
      }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)

instance HsProtobuf.Named SubscribeSingleInvoiceRequest where
  nameOf _ = (Hs.fromString "SubscribeSingleInvoiceRequest")

instance HsProtobuf.HasDefault SubscribeSingleInvoiceRequest

instance HsProtobuf.Message SubscribeSingleInvoiceRequest where
  encodeMessage
    _
    SubscribeSingleInvoiceRequest
      { subscribeSingleInvoiceRequestRHash =
          subscribeSingleInvoiceRequestRHash
      } =
      ( Hs.mconcat
          [ ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                subscribeSingleInvoiceRequestRHash
            )
          ]
      )
  decodeMessage _ =
    (Hs.pure SubscribeSingleInvoiceRequest)
      <*> ( HsProtobuf.at
              HsProtobuf.decodeMessageField
              (HsProtobuf.FieldNumber 2)
          )
  dotProto _ =
    [ ( HsProtobuf.DotProtoField
          (HsProtobuf.FieldNumber 2)
          (HsProtobuf.Prim HsProtobuf.Bytes)
          (HsProtobuf.Single "r_hash")
          []
          ""
      )
    ]

instance HsJSONPB.ToJSONPB SubscribeSingleInvoiceRequest where
  toJSONPB (SubscribeSingleInvoiceRequest f2) =
    (HsJSONPB.object ["r_hash" .= f2])
  toEncodingPB (SubscribeSingleInvoiceRequest f2) =
    (HsJSONPB.pairs ["r_hash" .= f2])

instance HsJSONPB.FromJSONPB SubscribeSingleInvoiceRequest where
  parseJSONPB =
    ( HsJSONPB.withObject
        "SubscribeSingleInvoiceRequest"
        ( \obj ->
            (Hs.pure SubscribeSingleInvoiceRequest) <*> obj .: "r_hash"
        )
    )

instance HsJSONPB.ToJSON SubscribeSingleInvoiceRequest where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance HsJSONPB.FromJSON SubscribeSingleInvoiceRequest where
  parseJSON = HsJSONPB.parseJSONPB

instance HsJSONPB.ToSchema SubscribeSingleInvoiceRequest where
  declareNamedSchema _ =
    do
      let declare_r_hash = HsJSONPB.declareSchemaRef
      subscribeSingleInvoiceRequestRHash <- declare_r_hash Proxy.Proxy
      let _ =
            Hs.pure SubscribeSingleInvoiceRequest
              <*> HsJSONPB.asProxy declare_r_hash
      Hs.return
        ( HsJSONPB.NamedSchema
            { HsJSONPB._namedSchemaName =
                Hs.Just "SubscribeSingleInvoiceRequest",
              HsJSONPB._namedSchemaSchema =
                Hs.mempty
                  { HsJSONPB._schemaParamSchema =
                      Hs.mempty
                        { HsJSONPB._paramSchemaType =
                            HsJSONPB.SwaggerObject
                        },
                    HsJSONPB._schemaProperties =
                      HsJSONPB.insOrdFromList
                        [ ( "r_hash",
                            subscribeSingleInvoiceRequestRHash
                          )
                        ]
                  }
            }
        )
